### ISSUE TITLE
Neo-CLI non-interactive mode

### ISSUE THREAD

**Issue by Abilkk** [neo-project/neo-node#623]
How can I start CLI's non-interactive mode ?

**Comment by dns7030** [comment]
Hi, welcome to Neo ecosystem. Are you developing a project on Neo? Please add me on telegram @dnsblg to learn how we can promote your project.

**Comment by Tommo-L** [comment]
> How can I start CLI's non-interactive mode ?

@Abilkk  CLI has not yet supported non-interactive mode.

**Comment by Abilkk** [comment]
@Tommo-L Could you please tell if you have any ETA for adding a non-interactive mode? I'm developing a one-click application for Ankr. Due to our infrastructure we are not able to use interactive mode. We would be extremely grateful if you could add this feature in the near future.

**Comment by Tommo-L** [comment]
Thanks your suggestion, we can add this feature recently.

**Comment by Lichen9618** [comment]
> @Tommo-L Could you please tell if you have any ETA for adding a non-interactive mode? I'm developing a one-click application for Ankr. Due to our infrastructure we are not able to use interactive mode. We would be extremely grateful if you could add this feature in the near future.

I am trying to improve that function, but I didn't know what kind of environment Ankr runs on.
if you need one-click non-interactive application, how about docker images(link): 
[https://hub.docker.com/repository/docker/neongd/neo-cli](url)
if there is other situation, please let me know more details.

**Comment by Tommo-L** [comment]
@Abilkk Could you use it? Or we still need non-interactive mode?

**Comment by magick93** [comment]
@Tommo-L - yes we still need non-interactive mode.

Thanks

**Comment by Tommo-L** [comment]
Port to neo3.0

**Comment by chenzhitong** [comment]
neo-cli 3.0 already supports non-interactive mode startup.
https://github.com/neo-project/neo-node/blob/master/Neo.ConsoleService/ConsoleServiceBase.cs#L511-L562

The UserInteractive property reports false for a Windows process or a service like IIS that runs without a user interface. If this property is false, do not display modal dialogs or message boxes because there is no graphical user interface for the user to interact with.
see https://docs.microsoft.com/en-us/dotnet/api/system.environment.userinteractive?redirectedfrom=MSDN&view=netcore-3.1#System_Environment_UserInteractive

I was able to simulate a non-interactive startup using Visual Studio's "attach to process" method and it worked fine.

**Comment by Tommo-L** [comment]
Fixed by #651
